@url=http://localhost:3000/api/cat
GET {{url}} HTTP/1.1
Content-Type: application/json

####

GET {{url}}/1 HTTP/1.1
Content-Type: application/json

####


POST  {{url}} HTTP/1.1
Content-Type: application/json

{
  "id": 2,
  "kode": "002",
  "nama": "Cat Bagus Skali"
}

####

put  {{url}}/1 HTTP/1.1
Content-Type: application/json

{
  "id": 1,
  "kode": "002",
  "nama": "Cat Jelek"
}
####

DELETE {{url}}/1 HTTP/1.1
Content-Type: application/json

###