@url=http://localhost:3000/api/kondisi
@token =  bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFkbWluMTcwIiwiaWF0IjoxNzAyMjcwMTUzLCJleHAiOjE3MDIzNTY1NTN9.VenUrimmDwMPtUkpNSk6k__UEFM5POSkTqRTrflFOOU
GET {{url}} HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

####

GET {{url}}/1 HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

####


POST  {{url}} HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

{
  "id": 2,
  "kode": "002",
  "nama": "Samping sini"
}

####

put  {{url}}/1 HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

{
  "id": 3,
  "kode": "002",
  "nama": "Sebelah sini"
}
####

DELETE {{url}}/1 HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

###