@url=http://localhost:3000/api/konsumen
@token =  bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFkbWluMTcwIiwiaWF0IjoxNzI0MzEzOTk3LCJleHAiOjE3MjQ0MDAzOTd9.QhoXty6YurwTzTTIn8IeIiItlrStcZrTqq0YQ5Sssto
GET {{url}} HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

####

GET {{url}}/1 HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

####

POST  {{url}} HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

{
  "id": 2,
  "namaKonsumen": "Robert Kiyosaki",
  "alamat": "jln. Sudirman",
  "kontak": "08111",
  "email": "ocph23.test@gmail.com"
}

####

put  {{url}}/2 HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

{
  "id": 2,
  "namaKonsumen": "Roberts Kiyosaki",
  "alamat": "jln. Sudirman",
  "kontak": "08111",
  "email": "ocph23.test@gmail.com"
}
####

DELETE {{url}}/2 HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

###